# This file was generated by liblab | https://liblab.com/

from llama_game_sdk import LlamaGameSDK, Environment, LlamaColor, Direction

# Initialize the SDK client
sdk = LlamaGameSDK(
    access_token="YOUR_ACCESS_TOKEN",
    base_url=Environment.DEFAULT.value,
    timeout=10000
)

# Create a llama
llama = sdk.llamas.create_llama(name="Fluffy", color=LlamaColor.BLUE)
print(f"Created llama: {llama.name} with ID: {llama.id}")

# Add steps for the llama to reach the pen
steps = [
    {"direction": Direction.RIGHT, "steps": 2},
    {"direction": Direction.DOWN, "steps": 1},
    {"direction": Direction.RIGHT, "steps": 3},
    {"direction": Direction.UP, "steps": 2}
]

for step in steps:
    sdk.llamas.add_step(llama_id=llama.id, direction=step["direction"], steps=step["steps"])
    print(f"Added step: {step['direction']} {step['steps']} step(s)")

# Execute the steps to move the llama
result = sdk.llamas.move_llama(llama_id=llama.id)

# Output the result
print(f"Llama movement result:")
print(f"Final position: {result.final_position}")
print(f"Score: {result.score}")
print(f"Status: {result.status}")
